clc;clear;close all;
Gamma = -1;
tau = 0;
Em = 1;
w = 3000;
phii = pi;
phir = 2*pi;
phit = 0;
x = linspace(31.4,31.5,10000);
y = linspace(-1,3,10000);
t = linspace(0,10*pi,1000);
Ei = Em*cos(w*t+phii);
Er = Em*Gamma*cos(w*t+phir);
Et = Em*tau*cos(w*(t+15)+phit);
xlabel('传播方向');
ylabel('振动方向');
title('对理想介质的分界面的垂直入射');
hold on;
plot(t,Ei+1);
hold on;
plot(t,Er+1);
hold on;
plot(t+31.4,Et);
hold on;
plot(x,y,'ko');
hold on;
axis([0,40,-0.5,2.5]);
legend('入射波','反射波','透射波');
hold on;
